### ISSUE TITLE
Getting concurrent (with CompletableFuture) and functions

### ISSUE THREAD

**Issue by Arcratist** [stefan-zobel/streamsupport#11]
I need a full implementation of CompletableFuture and the functions package. I see the files are included but separate, how would I use these together?

**Comment by stefan-zobel** [comment]
I don't get it. Care to explain further what you want to achieve?

**Comment by Arcratist** [comment]
oh and I'm using shadowJar and relocating the packages from java8.util to java.util

**Comment by Arcratist** [comment]
Basically I'm usuing completeablefuture but it needs classes from java.util.function

`09-10 23:36:12.680 15203-15561/org.geysermc.app.android E/AndroidRuntime: FATAL EXCEPTION: Thread-983
    Process: org.geysermc.app.android, PID: 15203
    java.lang.NoClassDefFoundError: $r8$wrapper$java$util$function$BiConsumer$-WRP
        at com.nukkitx.network.raknet.RakNet.bind(RakNet.java:52)
        at com.nukkitx.protocol.bedrock.Bedrock.bind(Bedrock.java:33)
        at org.geysermc.connector.GeyserConnector.<init>(GeyserConnector.java:185)
        at org.geysermc.connector.GeyserConnector.start(GeyserConnector.java:286)
        at org.geysermc.app.android.geyser.GeyserAndroidBootstrap.onEnable(GeyserAndroidBootstrap.java:93)
        at org.geysermc.app.android.geyser.GeyserAndroidBootstrap.onEnable(GeyserAndroidBootstrap.java:71)
        at org.geysermc.app.android.service.GeyserService.lambda$onStartCommand$0$GeyserService(GeyserService.java:107)
        at org.geysermc.app.android.service.-$$Lambda$GeyserService$cbY8YF_0evFoRiqlgJQFbS3OTy0.run(lambda)
        at java.lang.Thread.run(Thread.java:818)`

    java.lang.NoClassDefFoundError: $r8$wrapper$java$util$function$BiConsumer$-WRP <-- what matters

**Comment by Arcratist** [comment]
I cloned the repo and tried to smash it all together but it doesnt dex when doing it like that

**Comment by stefan-zobel** [comment]
Does it compile to a Java 8 Jar using javac? If yes, I'm out.

"relocating from java8.util to java.util" ... How is that supposed to work?

**Comment by Arcratist** [comment]
What I'm really asking is how would I combine

https://github.com/stefan-zobel/streamsupport/tree/master/src/main/java/java8

with 

https://github.com/stefan-zobel/streamsupport/tree/master/src/cfuture/java/java8/util/concurrent

or how would I use them both with maven?

I'm very new to all of these development tools

**Comment by Arcratist** [comment]
and using 

task streamsupportJar (type: ShadowJar) {
    getArchiveClassifier().set('streamsupport')

    relocate 'java8.util', 'java.util'
    relocate 'java8.lang', 'java.lang'

    configurations = [project.configurations.streamsupport]
}

to relocate

**Comment by stefan-zobel** [comment]
Combining the two separate source trees into one and compiling with Maven to a Java 8 jar should work without problems.

**Comment by Arcratist** [comment]
When using your maven repo I can only access whats in the src/main/java

**Comment by Arcratist** [comment]
Not cfuture

**Comment by stefan-zobel** [comment]
What I meant with "How is that supposed to work?" was not how you do the bytecode rewriting technically.

What I was asking is, on which runtime / for which clients is that supposed in practice?

You are aware that the streamsupport version isn't even API-compatible with Java 8?

**Comment by Arcratist** [comment]
I'm trying to compile for android versions below api 24

**Comment by stefan-zobel** [comment]
Simply copy the cfuture stuff in the src/main/java/java8/util/concurrent folder and get rid of src/cfuture

**Comment by Arcratist** [comment]
when cloning and using https://jitpack.io/ it doesnt build

**Comment by stefan-zobel** [comment]
All of these projects have been in a single project historically. Should build just fine. Use Maven, don't try to be too clever.

**Comment by stefan-zobel** [comment]
"I'm trying to compile for android versions below api 24". How is such a client supposed to use the API?

`java.util.Stream.empty()`  wouldn't work for example.

`new ArrayList().stream()` wouldn't work either.

**Comment by Arcratist** [comment]
I was using the java9-concurrent-backport and it compiled fine, I was just missing classes

**Comment by stefan-zobel** [comment]
IMHO, you have it backwards. What one would normally do, is to rewrite a client that uses the official Java 8 API to use the streamsupport or android-retrostreams API under the hood. That's what tools like android-retrofix and ProGuard are doing.

**Comment by Arcratist** [comment]
import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

apply plugin: 'com.android.application'
apply plugin: 'org.anarres.jarjar'
apply plugin: "com.github.johnrengelman.shadow"

android {
    compileSdkVersion 28
    buildToolsVersion "29.0.3"

    defaultConfig {
        applicationId "org.geysermc.app.android"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode 100007 // Format 00.00.000    EG 1.0.1 -> 01.00.001 -> 0100001 -> 100001
        versionName "1.0.7-BETA"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

        applicationVariants.all { variant ->
            variant.outputs.all { output ->
                def newName = outputFileName

                newName = newName.replace("app-", "${variant.mergedFlavor.applicationId}-")
                newName = newName.replace("-release", "-${variant.versionName}")
                newName = newName.replace("-debug", "-${variant.versionName}-debug")

                outputFileName = newName
            }
        }
    }

    compileOptions {
        coreLibraryDesugaringEnabled true

        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    packagingOptions {
        exclude 'META-INF/INDEX.LIST'
        exclude 'META-INF/io.netty.versions.properties'
    }

    configurations {
        nnio
        streamsupport
    }
}

repositories {
    maven {
        url = uri('https://repo.nukkitx.com/maven-releases/')
    }

    maven {
        url = uri('https://repo.nukkitx.com/maven-snapshots/')
    }

    maven {
        url = uri('https://jitpack.io')
    }

    maven {
        url = uri('https://oss.sonatype.org/content/repositories/snapshots/')
    }

    mavenCentral()
}

task nnioJar (type: ShadowJar) {
    getArchiveClassifier().set('nnio')

    relocate 'org.lukhnos.nnio.file', 'java.nio.file'
    relocate 'org.lukhnos.nnio.channels', 'java.nio.channels'

    configurations = [project.configurations.nnio]
}

task streamsupportJar (type: ShadowJar) {
    getArchiveClassifier().set('streamsupport')

    relocate 'java9.util', 'java.util'

    configurations = [project.configurations.streamsupport]
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'com.google.android.material:material:1.2.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.0.1'
    implementation 'androidx.navigation:navigation-fragment:2.3.0'
    implementation 'androidx.navigation:navigation-ui:2.3.0'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    implementation 'androidx.preference:preference:1.1.1'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.2'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'

    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.0.10'

    compileOnly 'org.projectlombok:lombok:1.18.12'
    annotationProcessor 'org.projectlombok:lombok:1.18.12'

    implementation "com.fasterxml.jackson.core:jackson-databind:2.9.8"

    // Remove epoll, kqueue and fastutil from the protocol
    implementation ("com.nukkitx.protocol:bedrock-v408:2.6.0-SNAPSHOT") {
        exclude group: 'com.nukkitx.fastutil', module:'fastutil-common'
        exclude group: 'com.nukkitx.network', module:'common'
        exclude group: 'io.netty', module:'netty-transport-native-epoll'
        exclude group: 'io.netty', module:'netty-transport-native-kqueue'
    }

    // Include the updated common with the android fixes
    implementation 'com.nukkitx.network:common:1.6.20'

    // Implement the cleaned fastutil manually to prevent the error on release builds
    implementation files("${buildDir}/jarjar/fastutil-cleaned.jar") { builtBy 'jarjar-repackage_fastutil-cleaned.jar' }

    // Remove the duplicate classes and include fastutil-common
    compileOnly jarjar.repackage('fastutil-cleaned.jar') {
        from 'com.nukkitx.fastutil:fastutil-common:8.3.1'

        classDelete "it.unimi.dsi.fastutil.ints.IntIterator"
        classDelete "it.unimi.dsi.fastutil.longs.LongIterator"
        classDelete "it.unimi.dsi.fastutil.objects.ObjectIterator"
        classDelete "it.unimi.dsi.fastutil.booleans.BooleanIterator"
        classDelete "it.unimi.dsi.fastutil.bytes.ByteIterator"
        classDelete "it.unimi.dsi.fastutil.doubles.DoubleIterator"
        classDelete "it.unimi.dsi.fastutil.floats.FloatIterator"
    }

    // Core Geyser
    implementation ('org.geysermc:connector:1.1.0') {
        exclude group: 'com.nukkitx.fastutil', module:'fastutil-common'
    }

    // Load a remake of nnio to support earlier Android versions
    nnio 'com.github.rtm516:nnio:c7b291f4ca'
    implementation tasks.nnioJar.outputs.files

    // Load streamsupport to support earlier Android versions
    streamsupport 'net.sourceforge.streamsupport:java9-concurrent-backport:2.0.0' <---------- this worked for me but it was missing classes
    implementation tasks.streamsupportJar.outputs.files

    // slf4j port for Android
    implementation 'org.slf4j:slf4j-android:1.7.30'
}

**Comment by Arcratist** [comment]
At the bottom

**Comment by stefan-zobel** [comment]
java9-concurrent-backport is for Oracle / OpenJDK Java 8 only. **Not** Android. See that `The minimum runtime requirement is OpenJDK (Oracle) Java 8.`?

**Comment by Arcratist** [comment]
It works, other than the missing classes

**Comment by Arcratist** [comment]
Compiles fine

**Comment by stefan-zobel** [comment]
works != compiles

**Comment by Arcratist** [comment]
Yes I do understand that. It's currently 2:50 am and my brain is fried. I'll try to put into words my intentions and attempts sometime tomorrow. I'll continue to hack around. I do greatly appreciate your time though, so thank you for that.

**Comment by stefan-zobel** [comment]
It may work if Google's `desguar_jdk_libs` take care of the missing `sun.misc.Unsafe` methods. I wish you good luck with that.

**Comment by stefan-zobel** [comment]
Something like this?
[streamsupport-concurrent.zip](https://github.com/stefan-zobel/streamsupport/files/5232880/streamsupport-concurrent.zip)

**Comment by Arcratist** [comment]
Ill have to give it a shot later on but it looks about right.

**Comment by Arcratist** [comment]
Merging dex file containing classes with prefix 'j$.' with classes with any other prefixes is not allowed.
Stack trace:
com.android.tools.r8.errors.a: Merging dex file containing classes with prefix 'j$.' with classes with any other prefixes is not allowed.
	at com.android.tools.r8.ir.conversion.O.a(:84)
	at com.android.tools.r8.ir.conversion.O.a(:53)
	at com.android.tools.r8.graph.C.b(:40)
	at com.android.tools.r8.ir.conversion.O.b(:35)
	at com.android.tools.r8.utils.U0.a(:10)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
	Suppressed: java.util.concurrent.ExecutionException: com.android.tools.r8.errors.a: Merging dex file containing classes with prefix 'j$.' with classes with any other prefixes is not allowed.
		at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
		at com.android.tools.r8.utils.U0.a(:14)
		at com.android.tools.r8.utils.U0.a(:9)
		at com.android.tools.r8.ir.conversion.O.a(:10)
		at com.android.tools.r8.D8.d(:29)
		at com.android.tools.r8.D8.b(:1)
		at com.android.tools.r8.utils.W.a(:30)
		at com.android.tools.r8.D8.run(:11)
		at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:117)
		at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:102)
		at com.android.build.gradle.internal.tasks.DexMergingTaskRunnable.run(DexMergingTask.kt:441)
		at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:242)
		at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:50)
		at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:50)
		at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:63)
		at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:59)
		at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
		at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:59)
		at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
		at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
		at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
		at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
		at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
		at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
		at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
		at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
		at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
		at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
		at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:53)
		at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:200)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
		at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
		at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
		at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
		at java.lang.Thread.run(Thread.java:748)
	[CIRCULAR REFERENCE:com.android.tools.r8.errors.a: Merging dex file containing classes with prefix 'j$.' with classes with any other prefixes is not allowed.]

It contains what I need but it doesnt dex

**Comment by stefan-zobel** [comment]
That seems to be related to what you are doing in your build (coreLibraryDesugaring especially), not streamsupport. AFAIK, the classes with the 'j$.' prefix are desugared Java 8 core classes from `desugar_jdk_libs`, e.g. anything in `java.util.function` gets rewritten to `j$.util.function`

**Comment by Arcratist** [comment]
I'm currently at a loss as I'm very very new to these tools. I'm stuck at this point

**Comment by stefan-zobel** [comment]
I've no idea what you are trying to achieve.
I can only speculate that the Dex merger doesn't allow to merge a relocated `java8.util -> java.util` class / package with a `j§.util` class / package (which seems to be the wrong approch anyway). In that case, a last desperate try could be to use the official Java 8 `java.util.function` interfaces in the `java8.util.concurrent` package and see if that makes any difference.

**Comment by Arcratist** [comment]
We have libraries which heavily use CompletableFuture, My min api version is 21. The ideal is to have this app run on all versions that the game we're developing it for does. Which is why I need this so bad. I'll give your approach a shot

**Comment by stefan-zobel** [comment]
I don't believe that your relocation approach will work, but anyway, good luck with that.
Here is a version that uses the official Java 8 `java.util.function` interfaces.
[streamsupport-concurrent-0.0.2.zip](https://github.com/stefan-zobel/streamsupport/files/5239269/streamsupport-concurrent-0.0.2.zip)

**Comment by Arcratist** [comment]
Okay! So I can relocate the classes no problem, and I can compile and install on the device

E/AndroidRuntime: FATAL EXCEPTION: Thread-2106
    Process: org.geysermc.app.android, PID: 17121
    java.lang.NoClassDefFoundError: $r8$wrapper$java$util$function$BiConsumer$-WRP <---------
        at com.nukkitx.network.raknet.RakNet.bind(RakNet.java:52)
        at com.nukkitx.protocol.bedrock.Bedrock.bind(Bedrock.java:33)
        at org.geysermc.connector.GeyserConnector.<init>(GeyserConnector.java:185)
        at org.geysermc.connector.GeyserConnector.start(GeyserConnector.java:286)
        at org.geysermc.app.android.geyser.GeyserAndroidBootstrap.onEnable(GeyserAndroidBootstrap.java:93)
        at org.geysermc.app.android.geyser.GeyserAndroidBootstrap.onEnable(GeyserAndroidBootstrap.java:71)
        at org.geysermc.app.android.service.GeyserService.lambda$onStartCommand$0$GeyserService(GeyserService.java:107)
        at org.geysermc.app.android.service.-$$Lambda$GeyserService$cbY8YF_0evFoRiqlgJQFbS3OTy0.run(lambda)
        at java.lang.Thread.run(Thread.java:818)

Although I get this NoClassDefFoundError.

**Comment by stefan-zobel** [comment]
I don't know if this is related : https://issuetracker.google.com/issues/157681341

**Comment by Arcratist** [comment]
I don't think so, I'm looking further now though

**Comment by Arcratist** [comment]
According to this https://developer.android.com/studio/write/java8-support-table everything should be there, I don't know how I'd debug this also as again I'm very new to development tools (always just used eclipse)

**Comment by Arcratist** [comment]
I'm currently testing the fixes, updating android studio to 4.1 rc3

**Comment by Arcratist** [comment]
I have other issues now related to updating Android Studio, I'll attempt again tomorrow. Once again thank you very much for your time :)

**Comment by stefan-zobel** [comment]
Slightly improved version:
[streamsupport-concurrent-0.0.3.zip](https://github.com/stefan-zobel/streamsupport/files/5245081/streamsupport-concurrent-0.0.3.zip)

**Comment by Arcratist** [comment]
I'm unable to fix the NoClassDefFound error, I've upgraded android studio but can't fix it :(

**Comment by Arcratist** [comment]
Also I'll try that out

**Comment by stefan-zobel** [comment]
> I'm unable to fix the NoClassDefFound error, I've upgraded android studio but can't fix it :(

I'm running out of ideas, sorry ...

**Comment by Arcratist** [comment]
Oh don't worry about it :) I'm grateful for the help already received

**Comment by Arcratist** [comment]
The last version you sent me give me the Merging dex file containing classes with prefix 'j$.' with classes with any other prefixes is not allowed. thing again

**Comment by stefan-zobel** [comment]
> The last version you sent me give me the Merging dex file containing classes with prefix 'j$.' with classes with any other prefixes is not allowed. thing again

Interesting. Are you sure that is not a caching thing in the build?
I can make another version, but not immediately.

**Comment by Arcratist** [comment]
Yeah I clean and invalidated caches
Also use jitpack commits so I know its up to date

**Comment by stefan-zobel** [comment]
That's strange. I've dropped RecursiveAction / Task (both not needed) and replaced usages of java8.util.Objects by java.util.Objects (which should work).
Other than that, there are 2 minor changes which are possible on API level >= 21 but weren't in the original implementation that targeted API level >= 14.
Just use the 0.0.2-SNAPSHOT version in the meanwhile.

**Comment by stefan-zobel** [comment]
For what it's worth, I've played a little with an adapted version of `android-retrofuture` that is compiled directly to `java.util.concurrent`.
While I don't like that approach, it seemd to work in a very very simple quick-and-dirty test on API 21 and 29 emulators (didn't test that much).

If that is OK for you, good - use it at your own risk. But please note, that I won't give any support for this project as I really view it as an ugly hack. It is named `android-cfuture21-hack` and can be found here: https://github.com/retrostreams/android-cfuture21-hack

Regards,
Stefan

**Comment by Arcratist** [comment]
Still no luck, I'm guessing its an issue on my end but I just can't see what. I'm also completely unable to acquire assistance anywhere unfortunately

**Comment by stefan-zobel** [comment]
The "hack" also doesn't work? With a similar error?
I hate Android, really ...

**Comment by Arcratist** [comment]
Yeah it seems as if de-sugaring isn't actually including the java.util.function package at all :/

**Comment by Arcratist** [comment]
is it possible to have the classes in the function package in a different package and compile with them instead of the desugared ones?

**Comment by stefan-zobel** [comment]
Strange, the `j.u.function` package got included in all of my tests. It would only be possible to have the function interfaces in a different package if all the the code that uses `CompletableFuture` 1) always uses lambdas and never references the `j.u.function` package explicitly and 2) if it gets recompiled. In the latter case you can also start using `java8.util` / `java9.util` everywhere. So: not really :(

**Comment by stefan-zobel** [comment]
FWIW, recompiling or (bytecode) rewriting the libraries to use the implementation from the `java8/9` packages would also be safest thing to do. The downside is that you won't profit from any possible improvements in the real Android implementation on newer devices.

**Comment by Arcratist** [comment]
Is there any reference material you could send me as to how I'd do a bytecode rewrite?

**Comment by stefan-zobel** [comment]
Nope, I don't have any. Your best bet is probably to try out https://github.com/SgtSilvio/android-retrofix
I don't know if https://github.com/Guardsquare/proguard supports CompletableFuture now - in the past they could only do streams.

**Comment by stefan-zobel** [comment]
OTH, the fact that the `j.u.function` doesn't get included suggests that your build is fundamentally broken. Introducing further advanced tools at this stage is probably not the right step.

**Comment by Arcratist** [comment]
Going to fork the dependencies and just import the backport instead

**Comment by stefan-zobel** [comment]
That would certainly be the easiest approach

**Comment by stefan-zobel** [comment]
FWIW, I've managed to run 3 OpenJDK CompletableFuture unit tests against the "cfuture21-hack" on API 21 / 29 emulators.
All pass in both environments and they clearly show that on API 29 the real Android implementation is used and on API 21 the "cfuture21-hack" gets used. So, in principle, it seems doable.

I am bit surprised that on API 29 the presence of the "hack" classes in the APK doesn't lead to problems, they simply seem to get ignored.
