### ISSUE TITLE
Apply classpath exception to source files

### ISSUE THREAD

**Issue by dbrgn** [stefan-zobel/streamsupport#13]
Hi, thanks for maintaining this useful library!

You're publishing this library under "GPL + Classpath Exception" (as discussed in #3 and #4). The license text is as follows:

```
"CLASSPATH" EXCEPTION TO THE GPL

Certain source files distributed by Oracle America and/or its affiliates are
subject to the following clarification and special exception to the GPL, but
only where Oracle has expressly included in the particular source file's header
the words "Oracle designates this particular file as subject to the "Classpath"
exception as provided by Oracle in the LICENSE file that accompanied this code."

    Linking this library statically or dynamically with other modules is making
    a combined work based on this library.  Thus, the terms and conditions of
    the GNU General Public License cover the whole combination.

    As a special exception, the copyright holders of this library give you
    permission to link this library with independent modules to produce an
    executable, regardless of the license terms of these independent modules,
    and to copy and distribute the resulting executable under terms of your
    choice, provided that you also meet, for each linked independent module,
    the terms and conditions of the license of that module.  An independent
    module is a module which is not derived from or based on this library.  If
    you modify this library, you may extend this exception to your version of
    the library, but you are not obligated to do so.  If you do not wish to do
    so, delete this exception statement from your version.
```

This leads to a few questions:

- If this library was based on code written by Oracle or its affiliates, were the corresponding files marked as subject to the classpath exception? If yes, could this header be re-added to all files involved?
- Would you qualify as an affiliate of Oracle? If not, could the text be adjusted to include "maintainers of the streamsupport library at &lt;github URL&gt;"?

I only looked at the cfuture library (https://github.com/stefan-zobel/streamsupport/tree/master/src/cfuture). In that library, there is a package-info.java file which contains the license header and the classpath exception, however the exception explicitly mentions "Oracle designates this particular file as subject to the "Classpath" exception as provided by Oracle in the LICENSE file that accompanied this code". I'm not a lawyer, but based on this license text, it seems that the code is not effectively licensed under the classpath exception, only under the GPLv2.

Since that does not seem to match the intention of the developers (@stefan-zobel), the header (including the exception) should probably be added to all source files.

**Comment by stefan-zobel** [comment]
Hi Danilo,

I'm not a lawyer either and, no, I'm not affiliated with Oracle.

The source code is based on the [OpenJDK](https://github.com/openjdk/jdk/tree/master/src/java.base/share/classes/java/util) and the [JSR166](http://gee.cs.oswego.edu/cgi-bin/viewcvs.cgi/jsr166/src/main/java/util/) sources, **_not_** on the sources that are distributed with an Oracle JDK.
The JSR166 sources don't have the Oracle GPL+CE license header as they are licensed under the [creative commons license](https://creativecommons.org/publicdomain/zero/1.0/).
Note that the Classpath Exception usually **_doesn't_** apply to the OpenJDK **_tests_** - these are GPL only.

Apart from the JSR166 sources and the tests, could you give an example where the GPL+CE header is missing?

I'm not sure why you think 

> "the code is not effectively licensed under the classpath exception, only under the GPLv2"

or why you think that an extension like

>  "maintainers of the streamsupport library"

would be necessary. Can you explain?

Regards,
Stefan

**Comment by dbrgn** [comment]
Thanks for the quick reply! This is the [license text](https://github.com/stefan-zobel/streamsupport/blob/master/GPL_ClasspathException) of the classpath exception that is included in this repository:

![image](https://user-images.githubusercontent.com/105168/96733254-853a4c80-13b9-11eb-80d0-4bb7ef15427d.png)


The text states:

> (...) but only where Oracle has expressly included in the particular source file's header (...)

The source files for cfuture are here:

https://github.com/stefan-zobel/streamsupport/blob/master/src/cfuture/java/java8/util/concurrent/CompletableFuture.java
https://github.com/stefan-zobel/streamsupport/blob/master/src/cfuture/java/java8/util/concurrent/CompletionStage.java
https://github.com/stefan-zobel/streamsupport/blob/master/src/cfuture/java/java8/util/concurrent/CompletionStages.java
https://github.com/stefan-zobel/streamsupport/blob/master/src/cfuture/java/java8/util/concurrent/CompletionException.java

As far as I can tell, none of these files currently contain the classpath exception in the source file header. Thus, when looking only at the license text, I would have to assume that those files are not covered by the exception.

Regarding the wording of the classpath exception itself, the license text states (emphasis mine):

> Certain source files distributed by Oracle America and/or its affiliates are
> subject to the following clarification and special exception to the GPL, **but
> only where Oracle has expressly included in the particular source file's header
> the words "Oracle designates this particular file as subject to the "Classpath"
> exception as provided by Oracle in the LICENSE file that accompanied this code."**

So the way this is worded, the copyright owner is saying that the GPLv2 applies, except if Oracle decided to include a certain text in the source file header. Since oracle is not the copyright owner of the modifications, that doesn't really make sense.

Maybe it could be worded like this instead?

> The source files distributed with this library are subject to the "Classpaht" exception as provided in the LICENSE file that accompanied this code.

(Adding a license header to all source files as well certainly wouldn't hurt either.)

I'm sorry for this nitpicking, but I think this is an important issue when trying to include the code into any non-GPL project :)

**Comment by stefan-zobel** [comment]
Hi Danilo,

on the frst part of your reply:

Well, the CompletableFuture stuff is exclusively from JSR-166 CVS repository maintained by Doug Lea and Martin Buchholz. They are the intellectual "fathers" of almost everything that lives in _java.util.concurrent_ and they decided that their code is licensed under the _creative commons license_.

The OpenJDK project occasionally syncs their downstream copy with the version from the JSR-166 CVS and add their own Oracle GPL+CE header (retaining the original license note from Doug Lea).

So, I wouldn't worry about the JSR-166 sources. They are **_all_** under the creative commons license, which demands exactly nothing from any project whatever license it uses. Oracle is **not** the copyright holder of these files and has simply chosen to change the license terms whereas I haven chosen to _not_ change them.

If I don't add anything to a license header, it should be uderstood that I agree with the license terms of the original author and that these terms should extend to any code I may have added or changed within that file. So yes, technically the JSR-166 code is not GPLv2+CE, it really is the _creative commons license_.

Regards,
Stefan

**Comment by dbrgn** [comment]
Thanks for clarification! I just saw that the files have quite a few changes made by you (https://github.com/stefan-zobel/streamsupport/commits/master/src/cfuture/java/java8/util/concurrent), so I assumed that those were modifications on top of the existing JSR-166 sources.

Maybe in that case the license at https://github.com/stefan-zobel/streamsupport/blob/master/src/cfuture/pom.xml#L11-L16 could be adjusted accordingly :slightly_smiling_face:

**Comment by stefan-zobel** [comment]
Yes, you are right. I should clarify that the GPLv2(+CE) license only pertains to the parts that are not from JSR-166. Will do that.

Regarding the changes you can see in the git history, almost all of them are syncs with the upstream JSR-166 CVS repo.

Only the very first versions (which date back to April / May 2014), especially of the ForkJoin related stuff, has more or less significant deviations from the JSR-166 version contributed by me. You can't see these changes in the git history.

**Comment by dbrgn** [comment]
Ok, then it would be great if it would be clearly stated somewhere in the `streamsupport-cfuture` library sources (ideally in the source files themselves) that all code (including all modifications by project maintainers) is released under the CC-0 license :slightly_smiling_face: 

Sorry for the work I'm causing you, I'd love to ignore licenses, but unfortunately I have to verify them (for a commercial project).

**Comment by stefan-zobel** [comment]
OK, I can do that for the sources that originate from JSR-166

**Comment by dbrgn** [comment]
Thank you very much, @stefan-zobel!
