### ISSUE TITLE
Add automatic module name

### ISSUE THREAD

**Issue by Dunemaster** [stefan-zobel/streamsupport#14]
For better compatibility with JPMS and to prevent warnign like

 "Required filename-based automodules detected: [streamsupport-1.7.2.jar]. Please don't publish this project to a public artifact repository!"

**Comment by Dunemaster** [comment]
@stefan-zobel , I can do it, if you ok with the task

**Comment by Dunemaster** [comment]
@stefan-zobel , thanks!

**Comment by stefan-zobel** [comment]
See also https://github.com/stefan-zobel/streamsupport/issues/15
