### ISSUE TITLE
License

### ISSUE THREAD

**Issue by gonciarz** [stefan-zobel/streamsupport#3]
Is there any chance to release this library under more liberal license (e.g. LGPL v3)? 
It's almost impossible to include it to most commercial products.

**Comment by stefan-zobel** [comment]
@gonciarz

Note that the license is **not** GPL v2.

It's GNU General Public License, version 2, **with the Classpath Exception** (the license that OpenJDK uses).
AFAIK, that's even more liberal than LGPL v3 and it certainly doesn't preclude any usage in a commercial product.

See also https://github.com/streamsupport/streamsupport/issues/19

Regards,
Stefan

**Comment by gonciarz** [comment]
Thanks for an explanation. I would suggest to put a short note to Readme file. And thanks for your effort.

**Comment by stefan-zobel** [comment]
Yeah, I should probably add (and link to) the "LICENSE" file that I've always included in the downloads on the sourceforge site, like https://sourceforge.net/projects/streamsupport/files/1.6.2-stable/ for example.

Will do that. Other than that, it is explicitly mentioned at the bottom of the top page under the "LICENSE" heading.

Regards,
Stefan
