### ISSUE TITLE
Can not use stream.of API

### ISSUE THREAD

**Issue by zhoujian365** [stefan-zobel/streamsupport#7]
i didn't find a way to use the original Stream.of(T) API. Is there a way to use it in streamsupport?

**Comment by stefan-zobel** [comment]
Hi Zhou Jian,

http://static.javadoc.io/net.sourceforge.streamsupport/streamsupport/1.7.0/java8/util/stream/RefStreams.html

The static java.util.Stream interface methods are located in java8.util.RefStreams.
There you'll find Stream.of(T) and Stream.of(T...) as RefStreams.of(T) and RefStreams.of(T...)

HTH,
Stefan
